FROM node:slim

# set working directory in the container
WORKDIR /app

# copy package.json and package-lock.json
COPY package*.json pnpm-lock.yaml* ./

# install pnpm
RUN npm install -g pnpm

# install dependencies
RUN pnpm install

# copy the rest of the application
COPY . .

# Run tests
CMD [ "pnpm", "test" ]

