name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      DEPLOY_PATH: '/home/ubuntu/NodeSocial-API'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Ensure Repository Exists
        run: |
          if [ ! -d "$DEPLOY_PATH" ]; then
              git clone https://github.com/SymonMuchemi/NodeSocial-API.git $DEPLOY_PATH
          fi

      - name: Stop and remove existing containers
        run: |
          cd $DEPLOY_PATH
          sudo docker-compose down || true

      - name: Pull latest changes
        run: |
          cd $DEPLOY_PATH
          git pull origin main
      
      - name: Run tests inside container (if available)
        run: |
          cd $DEPLOY_PATH
          if grep -q "\"test\":" package.json; then
            docker build -t nodesocial-api .
            docker run --rm nodesocial-api npm test
          else
            echo "No test script found in package.json. Skipping tests."
          fi

      - name: Build and start containers
        run: |
          cd $DEPLOY_PATH
          sudo docker compose up --build -d
